<html>
  <head>
    <title></title>
  </head>
  
  <body>
    
    <h1>Quiénes somos</h1>
    
    <br><br>
    
    <?= $menus ?>
    
    <!--
      <a href='inicio.php'>Inicio</a>
      <a href='proyectos.php'>Proyectos</a>
      <a href='quienes-somos.php'>Quiénes somos.</a>
    -->
    
    <form action="#" method="GET">
      <input type="text" name="usuario">
      <input type="submit" value="Enviar">
    </form>

    
  </body>
</html>